import './js/spinner/spinner';
import './js/add-active-marker';
import './js/ukr-sprt/ukr-sprt-slider';
import './js/best_sellers_load';
import './js/category-list';
import './js/all-books-by-category';
// import './js/add-to-shopping-list';
import './js/theme-switcher';
// import './js/all-books-by-seemore/fetch-books-by-category-api';
// import './js/all-books-by-seemore/all-books-by-category';
import './js/shopping-list';
import './js/theme-switcher';
import './js/modal';
