import './js/spinner/spinner';
import './js/add-active-marker';
import './js/ukr-sprt/ukr-sprt-slider';
import './js/best_sellers_load';
import './js/category-list';
import './js/all-books-by-category';
import './js/theme-switcher';
import './js/handle-shopping-list-modal';
import './js/theme-switcher';
import './js/modal';
import './js/scroll-up'
import './js/mobile-menu';
import './js/shoping-list-body';
